### ISSUE TITLE
change to use aiohttp for client connections so that it is all async

### ISSUE THREAD

**Issue by RDMurray** [openscape-community/overscape-server#3]
I did try to create a pull request, but it seems like the permissions for openscape-community don't allow it. 

I have switched to aiohttp instead of requests, because requests is blocking and I think it was the cause of a lot of the errors that I previously saw. The branch is at [RDMurray/overscape-server](https://github.com/RDMurray/overscape-server)

Unfortunately it breaks tests for now. This is the branch currently running on soundscape.mur.org.uk

**Comment by steinbro** [comment]
Thanks! I hadn't appreciated the friction between the older synchronous libraries and the newer async code.  I got most of the tests passing in a new branch; just running into some issues with mocking responses. https://github.com/steinbro/overscape-server-async

**Comment by Oliver2213** [comment]
Added you to the @openscape-community/backend team, @RDMurray.

**Comment by RDMurray** [comment]
thanks @Oliver2213 , however I think it should be possible to fork a repo and make pull requests without being part of the team. This is the first time I've been unable to fork a repo on github.

**Comment by Oliver2213** [comment]
Yeah, I am a little confused by that. I haven't done anything to prevent it in the settings; if there's something I can do to fix it, let me know. I'll go through and see if there's something I can toggle.

**Comment by RDMurray** [comment]
I think it might be in the repository settings. I still can't fork overscape-server.

To tidy things up, I deleted my copy of the repo at RDMurray/overscape-server and created an async branch in the original repo.

**Comment by steinbro** [comment]
Hm, not sure what the deal is with unforkability. But since you're an organization member, just creating a new branch in the main repository is a fine approach.

I got the tests passing and merged your changes. Thanks again!
